yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='posts_index'),
    path('group/<slug:slug>/', views.group_posts, name='posts_group_posts')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Главная страница
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50)
    description = models.TextField(blank=True, null=True,)

    def __str__(self) -> str:
        return (self.title)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


# Главная страница
def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    template = 'posts/index.html'
    context = {
        'posts': posts,
        'text': 'Последние обновления на сайте'
    }
    return render(request, template, context)


# Страница со списком постов, отфильрованных по группам
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    {% block title %}
      <title>YaTube</title>
    {% endblock %}
  </head>
  <body>    
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main> 
      {% block group %}
      {% endblock %}

      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>         
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<div class = 'border-top text-center py-3'>
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
</div>

yatube/templates/includes/header.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
    <a class="navbar-brand" href="{% url 'posts:posts_index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:Red">Ya</span>tube
    </a>
    </div>
</nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
  <div class = 'container'>
    <h1>{{group.title}}</h1>
    <p>
      {{group.description}}
    </p> 
    <article>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>    
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
    </article>
  </div>
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% comment %} {% block title %}
  <title>{{title}}</title>
{% endblock %} {% endcomment %}
{% block content %}
  <div class = 'container'>
    <h1>{{text}}</h1>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      {% if post.group %}   
        <a href="{% url 'posts:posts_group_posts' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
    </div>
{% endblock %}